import { ArrowLeft, Check, Minus, Plus, ShoppingBag, Star } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api } from "../api";
import { useApp } from "../context/AppContext";

export default function ProductDetails() {
  const { id } = useParams();
  const { addToCart } = useApp();
  const [product, setProduct] = useState(null);
  const [quantity, setQuantity] = useState(1);
  const [added, setAdded] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { api(`/products/${id}`).then(setProduct).catch((e) => setError(e.message)); }, [id]);
  const add = () => { for (let index = 0; index < quantity; index += 1) addToCart(product); setAdded(true); window.setTimeout(() => setAdded(false), 1800); };
  if (error) return <section className="mx-auto max-w-6xl px-5 py-24"><Link className="inline-flex items-center gap-2 text-sm font-bold text-coral" to="/menu"><ArrowLeft size={17} /> Back to menu</Link><h1 className="mt-6 font-display text-5xl">That item has gone missing.</h1><p className="mt-3 text-stone-500">{error}</p></section>;
  if (!product) return <section className="mx-auto max-w-6xl px-5 py-24 text-center text-stone-500">Preparing something lovely…</section>;
  return <section className="mx-auto max-w-6xl px-5 py-10 md:py-16"><Link className="inline-flex items-center gap-2 text-sm font-bold text-stone-500 transition hover:text-coral" to="/menu"><ArrowLeft size={17} /> Back to menu</Link><div className="mt-8 grid gap-10 lg:grid-cols-[1.08fr_.92fr] lg:items-center"><div className="relative grid min-h-[350px] place-items-center overflow-hidden rounded-[2.5rem] p-8 md:min-h-[500px]" style={{ background: `radial-gradient(circle at 30% 25%, #fff8e8, transparent 32%), linear-gradient(145deg, ${product.color}, #f9e6c4)` }}><div className="absolute inset-6 rounded-[2rem] border border-white/45" /><span className="relative text-[11rem] drop-shadow-2xl md:text-[16rem]">{product.emoji}</span><span className="absolute bottom-6 left-6 rounded-full bg-white/80 px-4 py-2 text-xs font-bold uppercase tracking-widest text-cocoa">Made fresh to order</span></div><div><p className="text-xs font-bold uppercase tracking-[.2em] text-coral">{product.category}</p><h1 className="mt-3 font-display text-5xl leading-none text-cocoa md:text-6xl">{product.name}</h1><div className="mt-5 flex items-center gap-3"><span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-3 py-1.5 text-sm font-bold text-amber-700"><Star className="fill-amber-400 text-amber-400" size={16} /> {product.rating} loved it</span><span className="text-sm text-stone-500">Freshly prepared</span></div><p className="mt-7 max-w-md text-lg leading-8 text-stone-600">{product.description} Thoughtfully made in our kitchen with the kind of ingredients we’re proud to serve.</p><div className="mt-8 rounded-2xl border border-stone-200 bg-white p-5"><p className="text-sm font-bold text-cocoa">What makes it special</p><div className="mt-4 grid gap-3 text-sm text-stone-600 sm:grid-cols-2"><p className="flex gap-2"><Check size={17} className="shrink-0 text-moss" /> Prepared after you order</p><p className="flex gap-2"><Check size={17} className="shrink-0 text-moss" /> Ready in 20–25 minutes</p></div></div><div className="mt-8 flex flex-wrap items-center gap-5"><div className="flex items-center rounded-full border border-stone-200 bg-white p-1"><button onClick={() => setQuantity(Math.max(1, quantity - 1))} className="grid h-10 w-10 place-items-center rounded-full hover:bg-stone-100" aria-label="Reduce quantity"><Minus size={18} /></button><span className="w-8 text-center font-bold">{quantity}</span><button onClick={() => setQuantity(quantity + 1)} className="grid h-10 w-10 place-items-center rounded-full hover:bg-stone-100" aria-label="Increase quantity"><Plus size={18} /></button></div><button onClick={add} className="inline-flex min-w-52 items-center justify-center gap-2 rounded-full bg-cocoa px-6 py-4 text-sm font-bold uppercase tracking-wide text-white transition hover:bg-coral"><ShoppingBag size={18} /> {added ? "Added to basket" : `Add · ₹${product.price * quantity}`}</button></div></div></div></section>;
}
